#! /usr/bin/env python

import argparse
import edge

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",  help="input image path")
    parser.add_argument("--output", help="output image path")
    args = parser.parse_args()

    if args.input and args.output:
        edge.edge_detection(args.input, args.output)

if __name__ == "__main__":
    main()
